# Site settings
author: Patrick M.
title: Programming : Frowns, then Happiness
header-img: img/home-bg.png
email: pa.mccombs1@gmail.com
copyright_name: Patrick M.
description: > # this means to ignore newlines until "baseurl:"
  Frowns First
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  pamccombs

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
